### PR TITLE
Add devcontainer development environment

### PR DESCRIPTION
**Pull request by haysch**
Based on issue #165 .

This PR adds support for devcontainer development environment in order to lower the barrier of entry to `NRedisStack`.

### CODE REVIEW

**Comment by shacharPash** [comment]
I think it should also be added to CONTRIBUTING.md a basic explanation of how to use devcontainer to make it easier for people to contribute code.

**Comment by haysch** [comment]
Local tests are now working in VS Code after the introduction of the skipping attribute.

Wrote a short section in `CONTRIBUTING.md`, please let me know if you think anything is missing!

**Comment by shacharPash** [comment]
Hey @haysch good job!
I added a more practical explanation about the use of dev containers.
What do you think?
And if there are inaccuracies or something wrong, you are welcome to correct/improve

**Comment by haysch** [comment]
@shacharPash great extension/explanation!
I don't have anything more to add - hopefully someone will find it as useful as I have!

**Review by shacharPash — APPROVED** [review]
LGTM 👍

**Pull request merged**
