### PR TITLE
Doc 2646 streams tutorial code examples in C#

### PR DESCRIPTION
**Pull request by andy-stark-redis**
My first PR at Redis :-)

The code seems to display OK in the doc page but no doubt my coding style isn't quite right yet :-)

### CODE REVIEW

**Review by dwdougherty — COMMENTED** [review]
The docs build correctly. So, apart from check issues, this looks good to me.

**Comment by shacharPash** [comment]
Closes #221

**Review by shacharPash — APPROVED** [review]
LGTM :)

**Comment by shacharPash** [comment]
Why the title is in 'c'? you meant C#?

**Comment by andy-stark-redis** [comment]
> @andy-stark-redis , Why the title is in 'c'? you meant C#?

Yes, it was auto-generated by JIRA and I forgot to edit it! I've changed it now :-)

**Pull request merged**
